name: Java CI with Gradle
on:
  push:
    tags: 
      - '*-release'
      - '*-pre'
jobs:   
  gradle:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set Up JRE
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        check-latest: true
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run build with Gradle wrapper
      run: ./gradlew build
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/libs/*.jar"
        prerelease: ${{ endsWith( github.ref_name, 'pre' ) }}
